### PR TITLE
Add an option to disable the "recheck" part of the comment

### PR DESCRIPTION
**Pull request by kingthorin**
We've found that due to the suggestion in the action's comment that users' comment "recheck" we've ended up with everyone commenting their agreement immediately followed by commenting recheck. Or, commenting both in the same comment. Therefore we'd like the option to disable the "recheck" suggestion.

Note: I have very little experience with GitHub action creation/contribution, if I've edited something I shouldn't have then please let me know, or conversely missed editing something I should have.

Prepared via: dev.github.com
Modeled mainly based on `lock-pullrequest-aftermerge` handling.

### CODE REVIEW

**Comment by kingthorin** [comment]
Hmmm I have no idea why so much of dist/index.js is showing changes. Perhaps dev.github.com adjusted line endings?

**Comment by kingthorin** [comment]
That seems to be what it is. If I choose “Hide white space” when viewing the diff then it appears as expected. I’ll look at pulling it into a real editor and fixing it.

**Comment by kingthorin** [comment]
I don't seem to be able to revert whatever those white space changes were. The only changes I actually implemented were on line < 1100

**Comment by kingthorin** [comment]
@ibakshay sorry to be pushy, I know ppl are busy with life. But, this would really help us and hopefully others too.

**Comment by ibakshay** [comment]
@kingthorin, I apologise for a LATE response. i was on vacation during August and then life happened. 
I really appreciate your PR! I tested in my test repository and I found out that the fix doesn't work as expected. I am getting an error - [link to the test workflow run](https://github.com/ibakshay/cla-test/actions/runs/10903837084/job/30258819251?pr=43). 

Tip: 
You have to add an if check in these two places. 

1. https://github.com/contributor-assistant/github-action/blob/f41946747f85d28e9a738f4f38dbcc74b69c7e0e/src/pullrequest/pullRequestCommentContent.ts#L54
2. https://github.com/contributor-assistant/github-action/blob/f41946747f85d28e9a738f4f38dbcc74b69c7e0e/src/pullrequest/pullRequestCommentContent.ts#L96

**Comment by kingthorin** [comment]
Thanks I'll get those adjusted too!

**Comment by kingthorin** [comment]
Hopefully that's it 😀

**Comment by ibakshay** [comment]
> Hopefully that's it 😀

You should also add the input to this `action.yml` file :) 
https://github.com/contributor-assistant/github-action/blob/master/action.yml

**Comment by kingthorin** [comment]
No problem, thanks for your help

**Comment by kingthorin** [comment]
Addressed.

**Comment by ibakshay** [comment]
> Addressed.

thanks a lot. Could you please do `npm run build`and then push again? 
You will see some changes in `dist/index.js` after you did `npm run build`.

**Comment by kingthorin** [comment]
Yup I'll have to setup a Linux image, I was doing this all via GitHub.dev

**Comment by kingthorin** [comment]
I was able to do it in a CodeSpace 😀 Hopefully that looks as you expected?

**Comment by ibakshay** [comment]
> I was able to do it in a CodeSpace 😀 Hopefully that looks as you expected?

It works great. Thanks so much for your contribution! I really appreciate it very much 🚀

**Review by ibakshay — APPROVED** [review]
🚀

**Comment by kingthorin** [comment]
Thanks for helping move this along. Sadly a colleague pointed out this may have broken things because the bot “signature” is left off but used as a condition elsewhere. 

https://github.com/contributor-assistant/github-action/blob/0fb69428196877a50810c3f5448ba84b2d15b058/src/pullrequest/pullRequestComment.ts#L64-L67

I’ll get a fix PR in today.

**Pull request merged**
