### PR TITLE
Add owner and repo variables to commit message template

### PR DESCRIPTION
**Pull request by silviogutierrez**

### CODE REVIEW

**Comment by silviogutierrez** [comment]
This is actually wrong, it shouldn't use the owner/repo variables, but rather the source repository.

**Comment by silviogutierrez** [comment]
I will update it

**Comment by silviogutierrez** [comment]
Confirming this works correctly now, which let's a remote repo has a nice commit log linking not just to the issue but the actual repo, making it clickable.

Like so:

image

Let me know if anything else is needed.

**Comment by ibakshay** [comment]
Thanks a lot for your contribution :) . I will check your PR this week and get back to you!

**Review by ibakshay — APPROVED** [review]

**Comment by ibakshay** [comment]
Hi @silviogutierrez,
Thanks a lot for your valuable contribution! 🍾

**Pull request merged**
